
/**
 * SCRIPT MySQL for creating the schema `jpa-app` and the related tables
 * 
 */

CREATE SCHEMA `jpa-app`;
  

CREATE TABLE ACCOUNT (
  ID  INT(11) NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  PASSWORD VARCHAR(255),
  ROLE VARCHAR(40),
  PRIMARY KEY (ID)
);


CREATE TABLE ADDRESS (
	ADDRESS_ID  INT(11) NOT NULL AUTO_INCREMENT,
    STREET_NAME VARCHAR(255),
    CITY_NAME VARCHAR(255),
    ZIP_CODE VARCHAR(255),
    STATE_NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PERSON (
	PERSON_ID  INT(11) NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    ADDRESS_ADDRESS_ID,
    PRIMARY KEY (ID) INT(11) NOT NULL,
    PRIMARY KEY (PERSON_ID)
);


CREATE TABLE EMPLOYEE (
	PERSON_ID  INT(11) NOT NULL AUTO_INCREMENT,
    SALARY INT(11),
    PRIMARY KEY (PERSON_ID)
);

